SELECT * FROM trips;
INSERT INTO trips (
	trip_location,
	trip_start_date,
	trip_end_date,
	trip_budget,
	trip_packing_list,
	trip_schedule
	)
VALUES ( $1, $2, $3, $4, $5, $6 );

-- {
-- 	"trip_location":"New York",
-- 	"trip_start_date":"07/12",
-- 	"trip_end_date":"08/13",
-- 	"trip_budget":"12",
-- 	"trip_packing_list":{"packingList":[
-- 		{"title": "Shirts", "isChecked": true},
-- 		{"title": "Shirts", "isChecked": true}
-- 	]},
-- 	"trip_schedule":{"tripSchedule":[
-- 		{"monday": [
-- 			{"title":"Drive to New York", "price":2.59, "isChecked":true},
-- 			{"title":"Breakfast", "price":3.99, "isChecked":false},
-- 			{"title":"Statue", "price":null, "isChecked":true}
-- 			]}
-- 		]}
-- }


-- {"tripSchedule":
-- 	[
-- 		{"week1":
-- 			[
-- 				{"mon": 
-- 					[
-- 						{"title": "Drive to New York", "price":2.59, "isChecked":true},
-- 						{"title":"Breakfast", "price":3.99, "isChecked":false},
-- 						{"title":"Statue", "price":null, "isChecked":true}
-- 					]
-- 				},
-- 				{"tue": 
-- 					[
-- 						{"title": "Drive to New York", "price":2.59, "isChecked":true},
-- 						{"title":"Breakfast", "price":3.99, "isChecked":false},
-- 						{"title":"Statue", "price":null, "isChecked":true}
-- 					]
-- 				},
-- 				{"wed": 
-- 					[
-- 						{"title": "Drive to New York", "price":2.59, "isChecked":true},
-- 						{"title":"Breakfast", "price":3.99, "isChecked":false},
-- 						{"title":"Statue", "price":null, "isChecked":true}
-- 					]
-- 				},
-- 				{"thurs": 
-- 					[
-- 						{"title": "Drive to New York", "price":2.59, "isChecked":true},
-- 						{"title":"Breakfast", "price":3.99, "isChecked":false},
-- 						{"title":"Statue", "price":null, "isChecked":true}
-- 					]
-- 				},
-- 				{"fri": 
-- 					[
-- 						{"title": "Drive to New York", "price":2.59, "isChecked":true},
-- 						{"title":"Breakfast", "price":3.99, "isChecked":false},
-- 						{"title":"Statue", "price":null, "isChecked":true}
-- 					]
-- 				},
-- 				{"sat": 
-- 					[
-- 						{"title": "Drive to New York", "price":2.59, "isChecked":true},
-- 						{"title":"Breakfast", "price":3.99, "isChecked":false},
-- 						{"title":"Statue", "price":null, "isChecked":true}
-- 					]
-- 				},
-- 				{"sun": 
-- 					[
-- 						{"title": "Drive to New York", "price":2.59, "isChecked":true},
-- 						{"title":"Breakfast", "price":3.99, "isChecked":false},
-- 						{"title":"Statue", "price":null, "isChecked":true}
-- 					]
-- 				},
-- 			]
-- 		},
		
-- 		{"week2":
-- 			[
-- 				{"mon": 
-- 					[
-- 						{"title": "Drive to New York", "price":2.59, "isChecked":true},
-- 						{"title":"Breakfast", "price":3.99, "isChecked":false},
-- 						{"title":"Statue", "price":null, "isChecked":true}
-- 					]
-- 				},
-- 				{"tue": 
-- 					[
-- 						{"title": "Drive to New York", "price":2.59, "isChecked":true},
-- 						{"title":"Breakfast", "price":3.99, "isChecked":false},
-- 						{"title":"Statue", "price":null, "isChecked":true}
-- 					]
-- 				},
-- 				{"wed": 
-- 					[
-- 						{"title": "Drive to New York", "price":2.59, "isChecked":true},
-- 						{"title":"Breakfast", "price":3.99, "isChecked":false},
-- 						{"title":"Statue", "price":null, "isChecked":true}
-- 					]
-- 				},
-- 				{"thurs": 
-- 					[
-- 						{"title": "Drive to New York", "price":2.59, "isChecked":true},
-- 						{"title":"Breakfast", "price":3.99, "isChecked":false},
-- 						{"title":"Statue", "price":null, "isChecked":true}
-- 					]
-- 				},
-- 				{"fri": 
-- 					[
-- 						{"title": "Drive to New York", "price":2.59, "isChecked":true},
-- 						{"title":"Breakfast", "price":3.99, "isChecked":false},
-- 						{"title":"Statue", "price":null, "isChecked":true}
-- 					]
-- 				},
-- 				{"sat": 
-- 					[
-- 						{"title": "Drive to New York", "price":2.59, "isChecked":true},
-- 						{"title":"Breakfast", "price":3.99, "isChecked":false},
-- 						{"title":"Statue", "price":null, "isChecked":true}
-- 					]
-- 				},
-- 				{"sun": 
-- 					[
-- 						{"title": "Drive to New York", "price":2.59, "isChecked":true},
-- 						{"title":"Breakfast", "price":3.99, "isChecked":false},
-- 						{"title":"Statue", "price":null, "isChecked":true}
-- 					]
-- 				}
-- 			]
-- 		}
-- 	]
-- }

-- {"tripSchedule":
-- 	[
-- 		{"week1":
-- 			[
-- 				{"mon":[]},
-- 				{"tue":[]},
-- 				{"wed":[]},
-- 				{"thur":[]},
-- 				{"fri":[]},
-- 				{"sat":[]},
-- 				{"sun":[]}
-- 			]
-- 		},
-- 		{"week2":
-- 			[
-- 				{"mon":[]},
-- 				{"tue":[]},
-- 				{"wed":[]},
-- 				{"thur":[]},
-- 				{"fri":[]},
-- 				{"sat":[]},
-- 				{"sun":[]}
-- 			]
-- 		}
-- 	]
-- }